### ISSUE TITLE
webview not deleting cookies

### ISSUE THREAD

**Issue by victor-zhang-000** [Kofktu/WKCookieWebView#2]
When I visit www.overstock.com, log in and then sign out, the status is still log in if I re-enter the app. I checked the cookies and found out the cookies could not be deleted on signing out.

**Comment by Kofktu** [comment]
@victor-zhang-000 
Fixed an issue where the cookie information was not updated when it was deleted.
Would you check with the `develop` branch?
If it works normally, we will release that version.

**Comment by Kofktu** [comment]
@victor-zhang-000 
1.0.1 release and available in CocoaPods 🎉
